export const dublinCoreMetadata = {
  "example metadata": "",
  "Title": "",
  "Description": "",
  "Creator": "",
  "Date": "",
  "Abstract": "",
  "Access Rights": "",
  "Accrual Method": "",
  "Accrual Periodicity": "",
  "Accrual Policy": "",
  "Alternative Title": "",
  "Audience": "",
  "Date Available": "",
  "Bibliographic Citation": "",
  "Conforms To": "",
  "Contributor": "",
  "Coverage": "",
  "Date Created": "",
  "Date Accepted": "",
  "Date Copyrighted": "",
  "Date Submitted": "",
  "Audience Education Level": "",
  "Extent": "",
  "Format": "",
  "Has Format": "",
  "Has Part": "",
  "Has Version": "",
  "Identifier": "",
  "Instructional Method": "",
  "Is Format Of": "",
  "Is Part Of": "",
  "Is Referenced By": "",
  "Is Replaced By": "",
  "Is Required By": "",
  "Date Issued": "",
  "Is Version Of": "",
  "Language": "",
  "License": "",
  "Mediator": "",
  "Medium": "",
  "Date Modified": "",
  "Provenance": "",
  "Publisher": "",
  "References": "",
  "Relation": "",
  "Replaces": "",
  "Requires": "",
  "Rights": "",
  "Rights Holder": "",
  "Source": "",
  "Spatial Coverage": "",
  "Subject": "",
  "Table Of Contents": "",
  "Temporal Coverage": "",
  "Type": "",
  "Date Valid": ""
}
